version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"  # Ensure your frontend runs on port 5173 inside the container
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: http://localhost:5000  # Ensure this points to the correct backend URL

  backend:
    build:
      context: ./backend
    ports:
      - "5000:8080"  # Map port 5000 on the host to port 8080 in the container
    volumes:
      - ./backend/data.db:/app/data.db
    environment:
      FLASK_ENV: production
      FLASK_APP: main.py
      FLASK_DEBUG: '1'
      FLASK_SECRET_KEY: 192b9bdd22ab9ed4d12e236c78afcb9a393ec15f71bbf5dc987d54727823bcbf
      FLASK_FRONTEND_URL: http://localhost:5173
      TEST_USERNAME: new
      TEST_PASSWORD: a206130940A
